horstoeko\ubl\entities\cac\CertificateOfOriginApplicationType:
    properties:
        referenceID:
            expose: true
            access_type: public_method
            serialized_name: ReferenceID
            xml_element:
                cdata: false
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getReferenceID
                setter: setReferenceID
            type: horstoeko\ubl\entities\cbc\ReferenceID
        certificateType:
            expose: true
            access_type: public_method
            serialized_name: CertificateType
            xml_element:
                cdata: false
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getCertificateType
                setter: setCertificateType
            type: horstoeko\ubl\entities\cbc\CertificateType
        applicationStatusCode:
            expose: true
            access_type: public_method
            serialized_name: ApplicationStatusCode
            xml_element:
                cdata: false
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getApplicationStatusCode
                setter: setApplicationStatusCode
            type: horstoeko\ubl\entities\cbc\ApplicationStatusCode
        originalJobID:
            expose: true
            access_type: public_method
            serialized_name: OriginalJobID
            xml_element:
                cdata: false
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getOriginalJobID
                setter: setOriginalJobID
            type: horstoeko\ubl\entities\cbc\OriginalJobID
        previousJobID:
            expose: true
            access_type: public_method
            serialized_name: PreviousJobID
            xml_element:
                cdata: false
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getPreviousJobID
                setter: setPreviousJobID
            type: horstoeko\ubl\entities\cbc\PreviousJobID
        remarks:
            expose: true
            access_type: public_method
            serialized_name: Remarks
            xml_element:
                cdata: false
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getRemarks
                setter: setRemarks
            type: horstoeko\ubl\entities\cbc\Remarks
        shipment:
            expose: true
            access_type: public_method
            serialized_name: Shipment
            xml_element:
                cdata: false
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            accessor:
                getter: getShipment
                setter: setShipment
            type: horstoeko\ubl\entities\cac\Shipment
        endorserParty:
            expose: true
            access_type: public_method
            serialized_name: EndorserParty
            xml_element:
                cdata: false
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            accessor:
                getter: getEndorserParty
                setter: setEndorserParty
            xml_list:
                inline: true
                entry_name: EndorserParty
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            type: array<horstoeko\ubl\entities\cac\EndorserParty>
        preparationParty:
            expose: true
            access_type: public_method
            serialized_name: PreparationParty
            xml_element:
                cdata: false
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            accessor:
                getter: getPreparationParty
                setter: setPreparationParty
            type: horstoeko\ubl\entities\cac\PreparationParty
        issuerParty:
            expose: true
            access_type: public_method
            serialized_name: IssuerParty
            xml_element:
                cdata: false
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            accessor:
                getter: getIssuerParty
                setter: setIssuerParty
            type: horstoeko\ubl\entities\cac\IssuerParty
        issuingCountry:
            expose: true
            access_type: public_method
            serialized_name: IssuingCountry
            xml_element:
                cdata: false
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            accessor:
                getter: getIssuingCountry
                setter: setIssuingCountry
            type: horstoeko\ubl\entities\cac\IssuingCountry
        documentDistribution:
            expose: true
            access_type: public_method
            serialized_name: DocumentDistribution
            xml_element:
                cdata: false
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            accessor:
                getter: getDocumentDistribution
                setter: setDocumentDistribution
            xml_list:
                inline: true
                entry_name: DocumentDistribution
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            type: array<horstoeko\ubl\entities\cac\DocumentDistribution>
        supportingDocumentReference:
            expose: true
            access_type: public_method
            serialized_name: SupportingDocumentReference
            xml_element:
                cdata: false
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            accessor:
                getter: getSupportingDocumentReference
                setter: setSupportingDocumentReference
            xml_list:
                inline: true
                entry_name: SupportingDocumentReference
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            type: array<horstoeko\ubl\entities\cac\SupportingDocumentReference>
        signature:
            expose: true
            access_type: public_method
            serialized_name: Signature
            xml_element:
                cdata: false
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            accessor:
                getter: getSignature
                setter: setSignature
            xml_list:
                inline: true
                entry_name: Signature
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            type: array<horstoeko\ubl\entities\cac\Signature>
