xsd2php:
  namespaces:
    'urn:oasis:names:specification:ubl:schema:xsd:Invoice-2': 'horstoeko\ubl\entities\main'
    'urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2': 'horstoeko\ubl\entities\ext'
    'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2': 'horstoeko\ubl\entities\cbc'
    'urn:oasis:names:specification:ubl:schema:xsd:QualifiedDatatypes-2': 'horstoeko\ubl\entities\qdt'
    'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2': 'horstoeko\ubl\entities\cac'
    'urn:oasis:names:specification:ubl:schema:xsd:UnqualifiedDataTypes-2': 'horstoeko\ubl\entities\udt'
    'urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2': 'horstoeko\ubl\entities\cct'
    'urn:oasis:names:specification:ubl:schema:xsd:CommonSignatureComponents-2': 'horstoeko\ubl\entities\csc'
    'urn:oasis:names:specification:ubl:schema:xsd:SignatureAggregateComponents-2': 'horstoeko\ubl\entities\sac'
    'urn:oasis:names:specification:ubl:schema:xsd:SignatureBasicComponents-2': 'horstoeko\ubl\entities\sbc'
    'http://www.w3.org/2000/09/xmldsig#': 'horstoeko\ubl\entities\ds'
    'http://uri.etsi.org/01903/v1.3.2#': 'horstoeko\ubl\entities\xades'
    'http://uri.etsi.org/01903/v1.4.1#': 'horstoeko\ubl\entities\xadesb'
  destinations_php: 
    'horstoeko\ubl\entities\main': '../src/entities/main'
    'horstoeko\ubl\entities\ext': '../src/entities/ext'
    'horstoeko\ubl\entities\cbc': '../src/entities/cbc'
    'horstoeko\ubl\entities\qdt': '../src/entities/qdt'
    'horstoeko\ubl\entities\cac': '../src/entities/cac'
    'horstoeko\ubl\entities\udt': '../src/entities/udt'
    'horstoeko\ubl\entities\cct': '../src/entities/cct'
    'horstoeko\ubl\entities\csc': '../src/entities/csc'
    'horstoeko\ubl\entities\sac': '../src/entities/sac'
    'horstoeko\ubl\entities\sbc': '../src/entities/sbc'
    'horstoeko\ubl\entities\ds': '../src/entities/ds'
    'horstoeko\ubl\entities\xades': '../src/entities/xades'
    'horstoeko\ubl\entities\xadesb': '../src/entities/xadesb'
  destinations_jms: 
    'horstoeko\ubl\entities\main': '../src/yaml/main'
    'horstoeko\ubl\entities\ext': '../src/yaml/ext'
    'horstoeko\ubl\entities\cbc': '../src/yaml/cbc'
    'horstoeko\ubl\entities\qdt': '../src/yaml/qdt'
    'horstoeko\ubl\entities\cac': '../src/yaml/cac'
    'horstoeko\ubl\entities\udt': '../src/yaml/udt'
    'horstoeko\ubl\entities\cct': '../src/yaml/cct'
    'horstoeko\ubl\entities\csc': '../src/yaml/csc'
    'horstoeko\ubl\entities\sac': '../src/yaml/sac'
    'horstoeko\ubl\entities\sbc': '../src/yaml/sbc'
    'horstoeko\ubl\entities\ds': '../src/yaml/ds'
    'horstoeko\ubl\entities\xades': '../src/yaml/xades'
    'horstoeko\ubl\entities\xadesb': '../src/yaml/xadesb'
  destinations_validation:
    'horstoeko\ubl\entities\main': '../src/validation/main'
    'horstoeko\ubl\entities\ext': '../src/validation/ext'
    'horstoeko\ubl\entities\cbc': '../src/validation/cbc'
    'horstoeko\ubl\entities\qdt': '../src/validation/qdt'
    'horstoeko\ubl\entities\cac': '../src/validation/cac'
    'horstoeko\ubl\entities\udt': '../src/validation/udt'
    'horstoeko\ubl\entities\cct': '../src/validation/cct'
    'horstoeko\ubl\entities\csc': '../src/validation/csc'
    'horstoeko\ubl\entities\sac': '../src/validation/sac'
    'horstoeko\ubl\entities\sbc': '../src/validation/sbc'
    'horstoeko\ubl\entities\ds': '../src/validation/ds'
    'horstoeko\ubl\entities\xades': '../src/validation/xades'
    'horstoeko\ubl\entities\xadesb': '../src/validation/xadesb'
  configs_jms:
    xml_cdata: false
  aliases:
    'http://www.w3.org/2001/XMLSchema':
      anyType: 'string'
      anySimpleType: 'string'
