xsd2php:
  namespaces:
    'urn:oasis:names:specification:ubl:schema:xsd:Invoice-2': 'horstoeko\ubl\entities\main'
    'urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2': 'horstoeko\ubl\entities\ext'
    'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2': 'horstoeko\ubl\entities\cbc'
    'urn:un:unece:uncefact:data:specification:UnqualifiedDataTypesSchemaModule:2': 'horstoeko\ubl\entities\udt'
    'urn:oasis:names:specification:ubl:schema:xsd:QualifiedDatatypes-2': 'horstoeko\ubl\entities\qdt'
    'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2': 'horstoeko\ubl\entities\cac'
    'urn:un:unece:uncefact:codelist:specification:66411:2001': 'horstoeko\ubl\entities\clm66411'
    'urn:un:unece:uncefact:codelist:specification:IANAMIMEMediaType:2003': 'horstoeko\ubl\entities\mimemedia'
    'urn:un:unece:uncefact:codelist:specification:54217:2001': 'horstoeko\ubl\entities\clm54217'
    'urn:un:unece:uncefact:codelist:specification:5639:1988': 'horstoeko\ubl\entities\clm5639'
  destinations_php: 
    'horstoeko\ubl\entities\main': '../src/entities/main'
    'horstoeko\ubl\entities\ext': '../src/entities/ext'
    'horstoeko\ubl\entities\cbc': '../src/entities/cbc'
    'horstoeko\ubl\entities\udt': '../src/entities/udt'
    'horstoeko\ubl\entities\qdt': '../src/entities/qdt'
    'horstoeko\ubl\entities\cac': '../src/entities/cac'
    'horstoeko\ubl\entities\clm66411': '../src/entities/clm66411'
    'horstoeko\ubl\entities\mimemedia': '../src/entities/mimemedia'
    'horstoeko\ubl\entities\clm54217': '../src/entities/clm54217'
    'horstoeko\ubl\entities\clm5639': '../src/entities/clm5639'
  destinations_jms: 
    'horstoeko\ubl\entities\main': '../src/yaml/main'
    'horstoeko\ubl\entities\ext': '../src/yaml/ext'
    'horstoeko\ubl\entities\cbc': '../src/yaml/cbc'
    'horstoeko\ubl\entities\udt': '../src/yaml/udt'
    'horstoeko\ubl\entities\qdt': '../src/yaml/qdt'
    'horstoeko\ubl\entities\cac': '../src/yaml/cac'
    'horstoeko\ubl\entities\clm66411': '../src/yaml/clm66411'
    'horstoeko\ubl\entities\mimemedia': '../src/yaml/mimemedia'
    'horstoeko\ubl\entities\clm54217': '../src/yaml/clm54217'
    'horstoeko\ubl\entities\clm5639': '../src/yaml/clm5639'
  destinations_validation:
    'horstoeko\ubl\entities\main': '../src/validation/main'
    'horstoeko\ubl\entities\ext': '../src/validation/ext'
    'horstoeko\ubl\entities\cbc': '../src/validation/cbc'
    'horstoeko\ubl\entities\udt': '../src/validation/udt'
    'horstoeko\ubl\entities\qdt': '../src/validation/qdt'
    'horstoeko\ubl\entities\cac': '../src/validation/cac'
    'horstoeko\ubl\entities\clm66411': '../src/validation/clm66411'
    'horstoeko\ubl\entities\mimemedia': '../src/validation/mimemedia'
    'horstoeko\ubl\entities\clm54217': '../src/validation/clm54217'
    'horstoeko\ubl\entities\clm5639': '../src/validation/clm5639'
  configs_jms:
    xml_cdata: false
  aliases:
    'http://www.w3.org/2001/XMLSchema':
      anyType: 'string'
      anySimpleType: 'string'
